In [1]:
import pandas as pd
import numpy as np
import  matplotlib.pyplot as plt
import seaborn as sns
import warnings 
import re
warnings.filterwarnings("ignore")

In [2]:
df1 = pd.read_csv("wedding.csv")
df1

,Name,Venue_Categories,Location,Ratings,Review,Price,Amenities
0,Jade Luxury Banquets,Sea View Banquet & Lawn,"Worli, Mumbai",5.0,(12 reviews),"₹3,200per plate",30-600 paxIndoorOutdoor+3 more
1,The Lalit Mumbai,5 Star Hotel,"Marol, Mumbai",NaN,(16 reviews),"₹3,800per plate",50-1000 pax389 Rooms+4 more
2,Kumar Resort by TURTLE,Resort Near Mumbai,Mumbai,5.0,(2 reviews),"₹1,499per plate",80-2000 pax90 Rooms+5 more
3,"Whistling Woodzs Jungle Resort, Dandeli",Lake View/River View\t,Mumbai,5.0,(2 reviews),₹999per plate,50-400 pax100 Rooms+3 more
4,Fairfield by Marriott Mumbai International Air...,Hotel with Banquet & Lawn,"Saki Naka, Mumbai",5.0,(3 reviews),"₹3,000per plate",50-1150 pax205 Rooms+5 more
...,...,...,...,...,...,...,...
2395,RP Palace,Wedding Lawn,Lucknow,NaN,No Reviews,₹400per plate,150-250 paxOutdoor+2 more
2396,Hotel Maharaja Delight Lawn,Lawn & Banquet Hall,Lucknow,NaN,No Reviews,Price on Request,100-400 pax15 Rooms+3 more
2397,Rajkamal Palace,Banquet Hall & Lawn,Lucknow,NaN,No Reviews,₹350per plate,200-400 paxIndoorOutdoor+2 more
2398,Shivaay Lawn,Wedding Lawn,Lucknow,NaN,No Reviews,₹700per plate,600-1000 paxOutdoor+2 more
2399,PS Lawn,Lawn & Banquet Hall,"Gomti Nagar, Lucknow",NaN,No Reviews,"₹1,30,000per function",60-800 paxIndoorOutdoor+3 more

In [3]:
df1.head(10)

,Name,Venue_Categories,Location,Ratings,Review,Price,Amenities
0,Jade Luxury Banquets,Sea View Banquet & Lawn,"Worli, Mumbai",5.0,(12 reviews),"₹3,200per plate",30-600 paxIndoorOutdoor+3 more
1,The Lalit Mumbai,5 Star Hotel,"Marol, Mumbai",NaN,(16 reviews),"₹3,800per plate",50-1000 pax389 Rooms+4 more
2,Kumar Resort by TURTLE,Resort Near Mumbai,Mumbai,5.0,(2 reviews),"₹1,499per plate",80-2000 pax90 Rooms+5 more
3,"Whistling Woodzs Jungle Resort, Dandeli",Lake View/River View\t,Mumbai,5.0,(2 reviews),₹999per plate,50-400 pax100 Rooms+3 more
4,Fairfield by Marriott Mumbai International Air...,Hotel with Banquet & Lawn,"Saki Naka, Mumbai",5.0,(3 reviews),"₹3,000per plate",50-1150 pax205 Rooms+5 more
5,Chandivali Studio,Wedding Lawn,Mumbai,NaN,(5 reviews),₹900per plate,500-800 paxOutdoor+3 more
6,Tarrang Banquets - Pure Veg,Banquet Hall,"Chembur, Mumbai",5.0,(9 reviews),"₹1,50,000per function",200-800 pax3 Rooms+5 more
7,Novotel Mumbai Juhu Beach,Sea Side Venue\t,"Juhu, Mumbai",NaN,(19 reviews),"₹4,500per plate",40-900 pax204 Rooms+5 more
8,Radisson Blu Mumbai International Airport,5 Star Hotel Near Airport,"Andheri East, Mumbai",5.0,(4 reviews),"₹3,000per plate",20-600 pax206 Rooms+4 more
9,Novotel Mumbai International Airport,Hotel Close To Airport,"Marol, Mumbai",4.5,(1 review),"₹3,000per plate",550-600 pax2 Rooms+5 more

In [4]:
df1.shape

(2400, 7)

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2400 entries, 0 to 2399
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              2400 non-null   object
 1   Venue_Categories  2382 non-null   object
 2   Location          2400 non-null   object
 3   Ratings           1274 non-null   float64
 4   Review            2400 non-null   object
 5   Price             2400 non-null   object
 6   Amenities         2400 non-null   object
dtypes: float64(1), object(6)
memory usage: 131.4+ KB

In [6]:
df1.isnull().sum()

Name                   0
Venue_Categories      18
Location               0
Ratings             1126
Review                 0
Price                  0
Amenities              0
dtype: int64

In [7]:
df1.apply(pd.Series.unique)

Name                [Jade Luxury Banquets, The Lalit Mumbai, Kumar...
Venue_Categories    [Sea View Banquet & Lawn, 5 Star Hotel, Resort...
Location            [Worli, Mumbai , Marol, Mumbai , Mumbai , Saki...
Ratings                           [5.0, nan, 4.5, 4.7, 4.9, 4.8, 4.6]
Review              [(12 reviews), (16 reviews), (2 reviews), (3 r...
Price               [₹3,200per plate, ₹3,800per plate, ₹1,499per p...
Amenities           [30-600 paxIndoorOutdoor+3 more, 50-1000 pax38...
dtype: object

In [8]:
regex = r"(\d+)\s*more"
df1["Amenties_more"] = df1["Amenities"].apply(lambda x: re.findall(regex,x)[0] if re.findall(regex,x) else None)
regex = r"(\d+)-"
df1["Capacity_min"] = df1["Amenities"].apply(lambda x: re.findall(regex,x)[0] if re.findall(regex,x) else None)
regex = r"(\d+)\s"
df1["Capacity_max"] = df1["Amenities"].apply(lambda x: re.findall(regex,x)[0] if re.findall(regex,x) else None)
regex = r"[\d,]+"
df1["Menu_price"] = df1["Price"].apply(lambda x: re.findall(regex,x)[0] if re.findall(regex,x) else None)
regex = r"(\d+)\s*Rooms"
df1["Rooms"] = df1["Amenities"].apply(lambda x: re.findall(regex,x)[0] if re.findall(regex,x) else None)
regex = r"(?:Mumbai|Pune|Bangalore|Chennai|Hyderabad|Lucknow|Delhi)"
df1["Destination"] = df1["Location"].apply(lambda x: re.findall(regex,x)[0] if re.findall(regex,x) else None)
regex = r"(\d+)"
df1["Reviews"] = df1["Review"].apply(lambda x: re.findall(regex,x)[0] if re.findall(regex,x) else None)
df1 = df1.drop("Price",axis=1)
df1 = df1.drop("Amenities",axis=1)
df1 = df1.drop("Review",axis=1)
df1 = df1[["Name","Venue_Categories","Destination","Ratings","Reviews","Menu_price","Capacity_min","Capacity_max","Rooms","Amenties_more"]]
df1["Ratings"]=pd.to_numeric(df1["Ratings"]) 
df1["Reviews"]=pd.to_numeric(df1["Reviews"]) 
df1["Capacity_min"]=pd.to_numeric(df1["Capacity_min"]) 
df1["Capacity_max"]=pd.to_numeric(df1["Capacity_max"]) 
df1["Rooms"] = pd.to_numeric(df1["Rooms"])
df1["Amenties_more"] = pd.to_numeric(df1["Amenties_more"])
df1["Menu_price"] = df1["Menu_price"].str.replace(",","")
df1["Menu_price"] = pd.to_numeric(df1["Menu_price"])
df1.duplicated().sum()
df1 = df1.drop_duplicates()
df1["Rooms"].fillna(df1["Rooms"].median(),inplace=True)
df1["Menu_price"].fillna(df1["Menu_price"].median(),inplace=True)
df1["Capacity_min"].fillna(df1["Capacity_min"].mean(),inplace=True)
df1["Reviews"].fillna(df1["Reviews"].mean(),inplace=True)
df1["Ratings"].fillna(df1["Ratings"].mean(),inplace=True)
df1["Venue_Categories"]=df1["Venue_Categories"].fillna(df1["Venue_Categories"].mode()[0])
df1

,Name,Venue_Categories,Destination,Ratings,Reviews,Menu_price,Capacity_min,Capacity_max,Rooms,Amenties_more
0,Jade Luxury Banquets,Sea View Banquet & Lawn,Mumbai,5.000000,12.000000,3200.0,30.0,600,20.0,3
1,The Lalit Mumbai,5 Star Hotel,Mumbai,4.927742,16.000000,3800.0,50.0,1000,389.0,4
2,Kumar Resort by TURTLE,Resort Near Mumbai,Mumbai,5.000000,2.000000,1499.0,80.0,2000,90.0,5
3,"Whistling Woodzs Jungle Resort, Dandeli",Lake View/River View\t,Mumbai,5.000000,2.000000,999.0,50.0,400,100.0,3
4,Fairfield by Marriott Mumbai International Air...,Hotel with Banquet & Lawn,Mumbai,5.000000,3.000000,3000.0,50.0,1150,205.0,5
...,...,...,...,...,...,...,...,...,...,...
2395,RP Palace,Wedding Lawn,Lucknow,4.927742,3.820106,400.0,150.0,250,20.0,2
2396,Hotel Maharaja Delight Lawn,Lawn & Banquet Hall,Lucknow,4.927742,3.820106,650.0,100.0,400,15.0,3
2397,Rajkamal Palace,Banquet Hall & Lawn,Lucknow,4.927742,3.820106,350.0,200.0,400,20.0,2
2398,Shivaay Lawn,Wedding Lawn,Lucknow,4.927742,3.820106,700.0,600.0,1000,20.0,2
2399,PS Lawn,Lawn & Banquet Hall,Lucknow,4.927742,3.820106,130000.0,60.0,800,20.0,3

In [9]:
df1.dtypes

Name                 object
Venue_Categories     object
Destination          object
Ratings             float64
Reviews             float64
Menu_price          float64
Capacity_min        float64
Capacity_max          int64
Rooms               float64
Amenties_more         int64
dtype: object

In [10]:
df1.isnull().sum()

Name                0
Venue_Categories    0
Destination         0
Ratings             0
Reviews             0
Menu_price          0
Capacity_min        0
Capacity_max        0
Rooms               0
Amenties_more       0
dtype: int64

In [12]:
df1["Menu_price"] = df1["Menu_price"].astype("int")
df1["Capacity_min"] = df1["Capacity_min"].astype("int")
df1["Capacity_max"] = df1["Capacity_max"].astype("int")
df1["Rooms"] = df1["Rooms"].astype("int")
df1["Reviews"] = df1["Reviews"].round(1)
df1["Ratings"] = df1["Ratings"].round(1)
df1.to_csv('cleaning.csv',index = False)
df1

,Name,Venue_Categories,Destination,Ratings,Reviews,Menu_price,Capacity_min,Capacity_max,Rooms,Amenties_more
0,Jade Luxury Banquets,Sea View Banquet & Lawn,Mumbai,5.0,12.0,3200,30,600,20,3
1,The Lalit Mumbai,5 Star Hotel,Mumbai,4.9,16.0,3800,50,1000,389,4
2,Kumar Resort by TURTLE,Resort Near Mumbai,Mumbai,5.0,2.0,1499,80,2000,90,5
3,"Whistling Woodzs Jungle Resort, Dandeli",Lake View/River View\t,Mumbai,5.0,2.0,999,50,400,100,3
4,Fairfield by Marriott Mumbai International Air...,Hotel with Banquet & Lawn,Mumbai,5.0,3.0,3000,50,1150,205,5
...,...,...,...,...,...,...,...,...,...,...
2395,RP Palace,Wedding Lawn,Lucknow,4.9,3.8,400,150,250,20,2
2396,Hotel Maharaja Delight Lawn,Lawn & Banquet Hall,Lucknow,4.9,3.8,650,100,400,15,3
2397,Rajkamal Palace,Banquet Hall & Lawn,Lucknow,4.9,3.8,350,200,400,20,2
2398,Shivaay Lawn,Wedding Lawn,Lucknow,4.9,3.8,700,600,1000,20,2
2399,PS Lawn,Lawn & Banquet Hall,Lucknow,4.9,3.8,130000,60,800,20,3

In [13]:
df1.dtypes

Name                 object
Venue_Categories     object
Destination          object
Ratings             float64
Reviews             float64
Menu_price            int64
Capacity_min          int64
Capacity_max          int64
Rooms                 int64
Amenties_more         int64
dtype: object

In [14]:
df1.duplicated().sum()

np.int64(0)

In [15]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2369 entries, 0 to 2399
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              2369 non-null   object
 1   Venue_Categories  2369 non-null   object
 2   Destination       2369 non-null   object
 3   Ratings           2369 non-null   float64
 4   Reviews           2369 non-null   float64
 5   Menu_price        2369 non-null   int64
 6   Capacity_min      2369 non-null   int64
 7   Capacity_max      2369 non-null   int64
 8   Rooms             2369 non-null   int64
 9   Amenties_more     2369 non-null   int64
dtypes: float64(2), int64(5), object(3)
memory usage: 203.6+ KB

In [16]:
df1.describe()

,Ratings,Reviews,Menu_price,Capacity_min,Capacity_max,Rooms,Amenties_more
count,2369.000000,2369.000000,2.369000e+03,2369.000000,2369.000000,2369.000000,2369.000000
mean,4.914732,3.812832,1.563824e+04,321.852258,805.810046,33.042634,2.729422
std,0.110847,7.166024,8.141019e+04,381.851537,962.018251,54.270884,0.786703
min,4.500000,1.000000,2.300000e+01,8.000000,4.000000,1.000000,1.000000
25%,4.900000,1.000000,5.000000e+02,100.000000,300.000000,20.000000,2.000000
50%,4.900000,3.800000,6.500000e+02,200.000000,500.000000,20.000000,3.000000
75%,5.000000,3.800000,1.000000e+03,400.000000,1000.000000,20.000000,3.000000
max,5.000000,212.000000,2.000000e+06,6000.000000,12000.000000,700.000000,8.000000

In [17]:
df1.apply(pd.Series.unique)

Name                [Jade Luxury Banquets, The Lalit Mumbai, Kumar...
Venue_Categories    [Sea View Banquet & Lawn, 5 Star Hotel, Resort...
Destination         [Mumbai, Pune, Bangalore, Chennai, Hyderabad, ...
Ratings                                [5.0, 4.9, 4.5, 4.7, 4.8, 4.6]
Reviews             [12.0, 16.0, 2.0, 3.0, 5.0, 9.0, 19.0, 4.0, 1....
Menu_price          [3200, 3800, 1499, 999, 3000, 900, 150000, 450...
Capacity_min        [30, 50, 80, 500, 200, 40, 20, 550, 100, 400, ...
Capacity_max        [600, 1000, 2000, 400, 1150, 800, 900, 500, 16...
Rooms               [20, 389, 90, 100, 205, 3, 204, 206, 2, 200, 1...
Amenties_more                                [3, 4, 5, 6, 2, 1, 7, 8]
dtype: object

In [18]:
numerical_columns = df1.select_dtypes(include= ['int64','float64']).columns.tolist()
categorical_columns= df1.select_dtypes(include= ['object']).columns.tolist()
numerical_columns, categorical_columns

(['Ratings',
  'Reviews',
  'Menu_price',
  'Capacity_min',
  'Capacity_max',
  'Rooms',
  'Amenties_more'],
 ['Name', 'Venue_Categories', 'Destination'])

In [19]:
print(numerical_columns)
print('-'*50)
print(categorical_columns)

['Ratings', 'Reviews', 'Menu_price', 'Capacity_min', 'Capacity_max', 'Rooms', 'Amenties_more']
--------------------------------------------------
['Name', 'Venue_Categories', 'Destination']

In [20]:
df1.head(10)

,Name,Venue_Categories,Destination,Ratings,Reviews,Menu_price,Capacity_min,Capacity_max,Rooms,Amenties_more
0,Jade Luxury Banquets,Sea View Banquet & Lawn,Mumbai,5.0,12.0,3200,30,600,20,3
1,The Lalit Mumbai,5 Star Hotel,Mumbai,4.9,16.0,3800,50,1000,389,4
2,Kumar Resort by TURTLE,Resort Near Mumbai,Mumbai,5.0,2.0,1499,80,2000,90,5
3,"Whistling Woodzs Jungle Resort, Dandeli",Lake View/River View\t,Mumbai,5.0,2.0,999,50,400,100,3
4,Fairfield by Marriott Mumbai International Air...,Hotel with Banquet & Lawn,Mumbai,5.0,3.0,3000,50,1150,205,5
5,Chandivali Studio,Wedding Lawn,Mumbai,4.9,5.0,900,500,800,20,3
6,Tarrang Banquets - Pure Veg,Banquet Hall,Mumbai,5.0,9.0,150000,200,800,3,5
7,Novotel Mumbai Juhu Beach,Sea Side Venue\t,Mumbai,4.9,19.0,4500,40,900,204,5
8,Radisson Blu Mumbai International Airport,5 Star Hotel Near Airport,Mumbai,5.0,4.0,3000,20,600,206,4
9,Novotel Mumbai International Airport,Hotel Close To Airport,Mumbai,4.5,1.0,3000,550,600,2,5

In [21]:
df1["Venue_Categories"].unique()

array(['Sea View Banquet & Lawn', '5 Star Hotel', 'Resort Near Mumbai',
       'Lake View/River View\t', 'Hotel with Banquet & Lawn',
       'Wedding Lawn', 'Banquet Hall', 'Sea Side Venue\t',
       '5 Star Hotel Near Airport', 'Hotel Close To Airport',
       '5 Star Resort Near Mumbai', 'Large Lawn & Banquet',
       'Luxury 5 Star Hotel', 'Banquet with Lawn', '4 Star Hotel',
       'Banquet Hall & Lawn', 'Large Wedding Lawn', 'Convention Hall',
       'Hotel with Large Banquet', 'Pillarless Banquet Hall',
       'Large Lawn with Banquet', 'Large Banquet Hall',
       'Lush Lawn & Banquet', 'Hotel with Banquet', 'Lawn & Banquet Hall',
       'Sea View 5 Star Hotel', 'Luxury Banquet Hall', 'Resort',
       'Luxury Sea View Hotel', 'Club / Cultural Center', 'Hotel',
       'Premium Banquet Hall', 'Hotel w/ Banquets & Lawn',
       'Party Restaurant / Lounge', 'Farmhouse',
       '4 Star & Above Wedding Hotels, Banquet Halls',
       'Party Restaurant & Lawn', 'Wedding Destination\t',
       'Resort Near Pune', 'Hotel W/ Banquets & Lawn',
       'Farmhouse with Banquet', 'Scenic Wedding Resort',
       'Resort with Banquet', 'Temple Wedding Venue', '5 Star Resort',
       'Farmhouse With Banquet', 'Small Function Hall',
       'Convention Hall & Lawn', 'Wedding Resort',
       'Scenic Lawn with Banquet', 'Rustic Luxe At Nandi Hills',
       'Retreat w/ Banquet & Lawn', 'Heritage Outdoor Venue',
       'Resort w/ Lawn & Banquet', 'Large City Center Banquet',
       'Hotel With Floating Mandap',
       'Banquet Halls, Marriage Garden / Lawns', 'Kalyana Mandapam',
       'Bali Themed Venue', 'Kalyana Mandapam With Lawn',
       'Fort / Palace Hotel', 'Lawn with Dome Structure',
       'Beach Front Resort', 'Homely Lawn with Banquet',
       'Seaside Luxury 5 Star', '4 Star Resort',
       'Lake View Lawn & Banquet', 'Large Indoor Banquets',
       'European-Style Lawn', '5 Star Convention Hall',
       '5 Star Fort / Palace Hotel', 'Convention Near Airport',
       'Banquet Halls', '5 Star River View Hotel'], dtype=object)

In [23]:
df1

,Name,Venue_Categories,Destination,Ratings,Reviews,Menu_price,Capacity_min,Capacity_max,Rooms,Amenties_more
0,Jade Luxury Banquets,Sea View Banquet & Lawn,Mumbai,5.0,12.0,3200,30,600,20,3
1,The Lalit Mumbai,5 Star Hotel,Mumbai,4.9,16.0,3800,50,1000,389,4
2,Kumar Resort by TURTLE,Resort Near Mumbai,Mumbai,5.0,2.0,1499,80,2000,90,5
3,"Whistling Woodzs Jungle Resort, Dandeli",Lake View/River View\t,Mumbai,5.0,2.0,999,50,400,100,3
4,Fairfield by Marriott Mumbai International Air...,Hotel with Banquet & Lawn,Mumbai,5.0,3.0,3000,50,1150,205,5
...,...,...,...,...,...,...,...,...,...,...
2395,RP Palace,Wedding Lawn,Lucknow,4.9,3.8,400,150,250,20,2
2396,Hotel Maharaja Delight Lawn,Lawn & Banquet Hall,Lucknow,4.9,3.8,650,100,400,15,3
2397,Rajkamal Palace,Banquet Hall & Lawn,Lucknow,4.9,3.8,350,200,400,20,2
2398,Shivaay Lawn,Wedding Lawn,Lucknow,4.9,3.8,700,600,1000,20,2
2399,PS Lawn,Lawn & Banquet Hall,Lucknow,4.9,3.8,130000,60,800,20,3